### ISSUE TITLE
MaxDepth param error

### ISSUE THREAD

**Issue by prasad2kin** [jprante/elasticsearch-aggregations#4]
If I don't specify min_depth & specify only max_depth parameter with value -1, I get an error saying "min_depth paramater must be lower than max_depth parameter".

It might be helpful if you could set condition to:

 if (**maxDepth != -1 &&** minDepth > maxDepth) {
            throw new ElasticsearchException("min_depth paramater must be lower than max_depth parameter");
        }

in PathParser.java#parse method.

**Comment by jprante** [comment]
Thanks. I have pushed version 2.1.1.1 with a fix.
